---
- name: create settings.js
  k8s:
    definition:
      apiVersion: v1
      kind: ConfigMap
      metadata:
        name: settings-configmap
        namespace: "{{ meta.namespace }}"
        labels:
          app: node-red-app
      data:
          settings.js: |
            module.exports = {
               uiPort: process.env.PORT || 1880,
               mqttReconnectTime: 15000,
               serialReconnectTime: 15000,
               debugMaxLength: 1000,
               flowFile: "{{ flowfilename  }}",
               credentialSecret: "{{ secretkey|b64decode if secretkey != 'false' else 'false'|bool }}",
               userDir: '/data',
               adminAuth: {
                   type: "credentials",
                   users: [{
                       username: "admin",
                       password: "{{ adminpassword }}",
                       permissions: "*"
                   }
                   {% for user in otherusers %}
                      ,{
                        username: "{{ user.username }}",
                        password: "{{ user.password }}",
                        permissions: "{{ user.permissions }}"
                       }
                    {% endfor %}
                   ]
               },
               functionGlobalContext: {
                  {% for module in functionglobalcontext %}
                    {% if loop.last %}
                      {{ module }}
                    {% else %}
                      {{ module }}, 
                    {% endif %}
                  {% endfor %}
               },
               exportGlobalContextKeys: false,
               logging: {
                 console: {
                   level: "info",
                   metrics: false,
                   audit: false
                  },
                  custom: {
                    level: 'info',
                    metrics: false,
                    handler: function(settings) {

                    var fs = require('fs');
                    return function(msg) {
                                                                                       
                      fs.appendFile('/var/log/node-red/nodered.log',JSON.stringify(msg)+"\n" , function (err) {
                      if (err) throw err;
                      }); 
                     }
                    }
                  }    
               },
               editorTheme: {
                 projects: {
                   enabled: false
                 }
               }
            }

