---
- name: create settings.js
  k8s:
    definition:
      apiVersion: v1
      kind: ConfigMap
      metadata:
        name: settings-configmap
        namespace: "{{ meta.namespace }}"
        labels:
          app: node-red-app
      data:
          settings.js: |
            module.exports = {
               uiPort: process.env.PORT || 1880,
               mqttReconnectTime: 15000,
               serialReconnectTime: 15000,
               debugMaxLength: 1000,
               credentialSecret: "{{ secretkey|b64decode if secretkey != 'false' else 'false'|bool }}",
               userDir: '/data',
               adminAuth: {
                   type: "credentials",
                   users: [{
                       username: "admin",
                       password: "{{ adminpassword }}",
                       permissions: "*"
                   }
                   {% for user in otherusers %}
                      ,{
                        username: "{{ user.username }}",
                        password: "{{ user.password }}",
                        permissions: "{{ user.permissions }}"
                       }
                    {% endfor %}
                   ]
               },
               functionGlobalContext: {
                 {% for node in functionglobalcontext %}
                   "{{ functionglobalcontext }}"
                 {% endfor %}
               },
               exportGlobalContextKeys: false,
               logging: {
                 console: {
                   level: "info",
                   metrics: false,
                   audit: false
                  }
               },
               editorTheme: {
                 projects: {
                   enabled: false
                 }
               }
            }

