---
# defaults file for noderedhelmansible
chart:
  apiVersion: v2
  name: nodered-chart
  description: A Helm chart to install Node-Red
  type: application
  version: 0.1.0
  appVersion: 1.0.6
image: quay.io/opentestlabs/node-red:1.0.6
imagePullSecrets: []
service:
  type: null
  name: node-red-svc
resources: {}
route: 
 enabled: true
 path: node-red
persistencevolume:
  enabled:  true
  storageclass: ibmc-block-bronze
  size: 100Mi
serviceAccount:
  name: node-red-ansible-operator