apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: noderedmonitors.nodered.com
spec:
  group: nodered.com
  names:
    kind: NodeRedMonitor
    listKind: NodeRedMonitorList
    plural: noderedmonitors
    singular: noderedmonitor
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      type: object
      x-kubernetes-preserve-unknown-fields: true
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
