apiVersion: nodered.com/v1alpha1
kind: NodeRed
metadata:
  name: nodered
spec:
  image: quay.io/opentestlabs/node-red:0.0.1
  service:
    type: null
    name: node-red-svc
  route:
    enabled: true
    path: node-red
  persistentvolume:
    enabled: false
    storageclass: ibmc-block-bronze
    size: 100Mi
