kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: node-red-operator-cluster-binding
subjects:
- kind: ServiceAccount
  name: node-red-operator
  namespace: node-red-p2
roleRef:
  kind: ClusterRole
  name: node-red-operator-clusterrole
  apiGroup: rbac.authorization.k8s.io

