apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: node-red-operator-clusterrole
  namespace: node-red-p2
rules:
- apiGroups:
  - security.openshift.io
  resources:
  - securitycontextconstraints
  resourceNames:
  - anyuid
  verbs:
  - use
