apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: noderedhelmansibles.nodered.com
spec:
  group: nodered.com
  names:
    kind: NodeRedHelmAnsible
    listKind: NodeRedHelmAnsibleList
    plural: noderedhelmansibles
    singular: noderedhelmansible
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      type: object
      x-kubernetes-preserve-unknown-fields: true
  versions:
  - name: v1alpha1
    served: true
    storage: true
