---
# defaults file for noderedhelmansible
chart:
  apiVersion: v2
  name: nodered-chart
  description: Operator to install Node-Red
  type: application
  version: 0.1.0
  appVersion: 1.0.6
image: image-registry.openshift-image-registry.svc:5000/node-red-p2/node-red:0.0.2
imagePullSecrets: []
service:
  type: null
  name: node-red-svc
route: 
 enabled: true
 path: node-red
persistentvolume:
  enabled:  true
  storageclass: ibmc-block-bronze
  size: 100Mi
adminpassword: $2a$08$lkNywjX07FEM4xzGsDXRfOGW80PtQKirmfXRTWHZslOL5zehrbmai
secretkey: c2VjcmV0
user:
  name: shraddha
  password: $2a$08$lkNywjX07FEM4xzGsDXRfOGW80PtQKirmfXRTWHZslOL5zehrbmai
  permission: read