---
# tasks file for noderedhelmansible
- name: set default volumes
  set_fact:
    volumeMounts:
      - mountPath: /usr/conf
        name: config-volume
    volumeNames:
      - configMap:
          name: settings-configmap
        name: config-volume

- block:
    - name: set volume
      set_fact:
        volumeMounts:
          - mountPath: /usr/conf
            name: config-volume
          - mountPath: /data
            name: data
        volumeNames:
          - configMap:
              name: settings-configmap
            name: config-volume
          - name: data
            persistentVolumeClaim:
              claimName:  node-red-pvc
  when: persistentvolume.enabled is defined and persistentvolume.enabled|bool == true

- name: create pvc
  when: persistentvolume.enabled is defined and persistentvolume.enabled|bool == true
  k8s:
     definition:
       apiVersion: v1
       kind: PersistentVolumeClaim
       metadata:
         name: node-red-pvc
         namespace: "{{ meta.namespace }}"
         labels:
           app: node-red-app
       spec:
         storageClassName: "{{ persistentvolume.storageclass }}"
         accessModes:
           - ReadWriteOnce
         resources:
           requests:
             storage: "{{ persistentvolume.size | quote }}"


- name: create config-map
  include_tasks: configmap.yaml


- name: deploy node-red
  k8s:
    definition:
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: node-red
        namespace: "{{ meta.namespace }}"
      spec:
        selector:
          matchLabels:
            app: node-red-app
        replicas: "{{ size }}"
        template:
          metadata:
            labels:
              app: node-red-app
          spec:
            imagePullSecrets:
            serviceAccountName: node-red-operator
            securityContext:
              fsGroup: 1000
            containers:
            - name: node-red
              image: "{{ image }}"
              imagePullPolicy: Always
              ports:
               - containerPort: 1880
              volumeMounts: "{{ volumeMounts }}"
            volumes: "{{ volumeNames }}"

- name: create service
  k8s:
    definition:
        apiVersion: v1
        kind: Service
        metadata:
          name: "{{ service.name }}"
          namespace: "{{ meta.namespace }}"
          labels:
            app: node-red-app
        spec:
          selector:
              app: node-red-app
          type: "{{ service.type }}"
          ports:
            - name: 1880-tcp
              protocol: TCP
              port: 1880
              targetPort: 1880

- name: create route
  when: route.enabled is defined and route.enabled|bool == true
  k8s:
    definition:
        apiVersion: route.openshift.io/v1
        kind: Route
        metadata:
          name: "{{ route.path }}"
          namespace: "{{ meta.namespace }}"
          labels:
            app: node-red-app
        spec:
          to:
            kind: Service
            name: "{{ service.name }}"
          port:
            targetPort: 1880-tcp
            
